blog/urls.py
from django.urls import path

from .views import (
        IndexView, 
        ArticleDetailView, 
        CategoryView, 
        TagView, 
        ArchiveView, 
        AboutView, 
        MySearchView, 
    )

app_name = 'blog'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # 主页，自然排序
    path('hot/', IndexView.as_view(), {'sort': 'v'}, name='index_hot'),  # 主页，按照浏览量排序
    path('article/<slug:slug>/', ArticleDetailView.as_view(), name='detail'),
    path('category/<slug:slug>/', CategoryView.as_view(), name='category'),
    path('category/<slug:slug>/hot/', CategoryView.as_view(), {'sort': 'v'}, name='category_hot'),
    path('tag/<slug:slug>/', TagView.as_view(), name='tag'),
    path('tag/<slug:slug>/hot/', TagView.as_view(), {'sort': 'v'}, name='tag_hot'),
    path('archive/', ArchiveView.as_view(), name='archive'),
    path('about/', AboutView, name='about'),
    path('search/', MySearchView.as_view(), name='search_view'),  # 全文搜索
]

oauth/urls.py
from django.urls import path
from .views import profile_view, change_profile_view

app_name = 'oauth'

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('profile/change/', change_profile_view, name='change_profile'),
]

oauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


class Ouser(AbstractUser):
    link = models.URLField('个人网址',blank=True,help_text='提示：网址必须填写以http开头的完整形式')
    avatar = ProcessedImageField(upload_to='avatar/%Y/%m/%d',
                                 default='avatar/default.png',
                                 verbose_name='头像',
                                 processors=[ResizeToFill(80, 80)]
                                 )

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return self.username

oauth/forms.py
from django import forms
from .models import Ouser

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Ouser
        fields = ['link', 'avatar']

oauth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .forms import ProfileForm
from django.contrib import messages


@login_required
def profile_view(request):
    return render(request, 'oauth/profile.html')


@login_required
def change_profile_view(request):
    if request.method == 'POST':
        # 上传文件需要使用request.FILES
        form = ProfileForm(request.POST,request.FILES,instance=request.user)
        if form.is_valid():
            form.save()
            # 添加一条信息,表单验证成功就重定向到个人信息页面
            messages.add_message(request,messages.SUCCESS,'个人信息更新成功！')
            return redirect('oauth:profile')
    else:
        # 不是POST请求就返回空表单
        form = ProfileForm(instance=request.user)
        context = {
            'form': form,
        }
    return render(request, 'oauth/change_profile.html',context)


oauth/templates/oauth/change_profile.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block top-file %}
    <link href="{% static 'blog/css/account.css' %}?v=20200531.01966" rel="stylesheet">
{% endblock %}

{% block head_title%}
    个人信息修改
{% endblock%}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3 px-xl-5">
            <div class="card rounded-0 px-3 px-lg-4">
                <div class="card-header text-center bg-white py-2"><h3 class="my-1 text-info">修改资料</h3></div>
                <div class="card-body">
                    <form class="change_profile" method="post" enctype="multipart/form-data"
                          action="{% url 'oauth:change_profile'%}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-info btn-sm rounded-0" type="submit">更新资料</button>
                    </form>
                </div>
                <div class="text-center mb-5" id="social-login">
                    <div class="login-title"><span>更多操作</span></div>
                    <div class="more-link mt-3">
                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="{% url 'oauth:profile' %}">查看资料</a>
                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="{% url 'account_change_password' %}">修改密码</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

oauth/templates/oauth/profile.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load blog_tags oauth_tags %}
{% load static %}

{% block top-file %}
    <link href="{% static 'blog/css/account.css' %}?v=2020531.01966" rel="stylesheet">
{% endblock %}

{% block head_title%}
    个人资料
{% endblock%}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3 px-xl-5">
            <div class="card rounded-0 px-3 px-lg-4">
                <div class="card-header text-center bg-white py-2"><h3 class="my-1 text-info">个人资料</h3></div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item text-center border-0" id="profile-avatar">
                            {% get_user_avatar_tag user %}
                        </li>
                        <li class="list-group-item ml-5 border-0">
                            <span class="font-weight-bold">用户名：</span>
                            <span>{{ user.username }}</span>
                        </li>
                        <li class="list-group-item ml-5 border-0">
                            <span class="font-weight-bold">邮&emsp;箱：</span>
                            <span>{{ user.email }}</span>
                        </li>
                        <li class="list-group-item ml-5 border-0">
                            <span class="font-weight-bold">网&emsp;址：</span>
                            <span>{{ user.link }}</span>
                        </li>
                    </ul>
                </div>
                <div class="text-center mb-5" id="social-login">
                    <div class="login-title"><span>更多操作</span></div>
                    <div class="more-link mt-3">
                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="{% url 'oauth:change_profile' %}">修改资料</a>
                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="{% url 'account_change_password' %}">修改密码</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

