blog/urls.py
from django.urls import path

from .views import (
        IndexView, 
        ArticleDetailView, 
        CategoryView, 
        TagView, 
        ArchiveView, 
        AboutView, 
        MySearchView, 
    )

app_name = 'blog'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # 主页，自然排序
    path('hot/', IndexView.as_view(), {'sort': 'v'}, name='index_hot'),  # 主页，按照浏览量排序
    path('article/<slug:slug>/', ArticleDetailView.as_view(), name='detail'),
    path('category/<slug:slug>/', CategoryView.as_view(), name='category'),
    path('category/<slug:slug>/hot/', CategoryView.as_view(), {'sort': 'v'}, name='category_hot'),
    path('tag/<slug:slug>/', TagView.as_view(), name='tag'),
    path('tag/<slug:slug>/hot/', TagView.as_view(), {'sort': 'v'}, name='tag_hot'),
    path('archive/', ArchiveView.as_view(), name='archive'),
    path('about/', AboutView, name='about'),
    path('search/', MySearchView.as_view(), name='search_view'),  # 全文搜索
]

comment/urls.py
from django.urls import path
from .views import (
        AddcommentView, 
        NotificationView, 
        mark_to_read, 
        mark_to_delete
    )

app_name = 'comment'

urlpatterns = [
    path('add/', AddcommentView, name='add_comment'),
    path('notification/', NotificationView, name='notification'),
    path('notification/no-read/', NotificationView, {'is_read': 'false'}, name='notification_no_read'),
    path('notification/mark-to-read/', mark_to_read, name='mark_to_read'),
    path('notification/mark-to-delete/', mark_to_delete, name='mark_to_delete'),
]

oauth/urls.py
from django.urls import path
from .views import profile_view, change_profile_view

app_name = 'oauth'

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('profile/change/', change_profile_view, name='change_profile'),
]

tools/urls.py
from django.urls import path

from .views import (
        TimelineView, 
        FriendLinkView, 
    )

app_name = 'tools'

urlpatterns = [
    path('timeline/', TimelineView.as_view(), name='timeline'),
    path('friendlink/', FriendLinkView.as_view(), name='friendlink'),
]

blog/models.py
import markdown
from django.db import models
from django.conf import settings
from django.urls import reverse


# 文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=20)
    slug = models.SlugField(unique=True)
    
    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag', kwargs={'slug': self.slug})

    def get_article_list(self):
        '''返回当前标签下所有发表的文章列表'''
        return Article.objects.filter(tags=self)


# 文章分类
class Category(models.Model):
    name = models.CharField('文章分类', max_length=20)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slug': self.slug})

    def get_article_list(self):
        '''返回当前分类下所有发表的文章列表'''
        return Article.objects.filter(category=self)


# 文章
class Article(models.Model):
    IMG_LINK = '/static/blog/img/summary.png'
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='作者')
    title = models.CharField(max_length=150, verbose_name='文章标题')
    summary = models.TextField('文章摘要', max_length=230, default='文章摘要等同于网页description内容，请务必填写...')
    body = models.TextField(verbose_name='文章内容')
    img_link = models.CharField('图片地址', default=IMG_LINK, max_length=255)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    views = models.IntegerField('阅览量', default=0)
    slug = models.SlugField(unique=True)

    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='文章分类')
    tags = models.ManyToManyField(Tag, verbose_name='标签')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return self.title[:20]

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

    def body_to_markdown(self):
        return markdown.markdown(self.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

    def update_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_pre(self):
        return Article.objects.filter(id__lt=self.id).order_by('-id').first()

    def get_next(self):
        return Article.objects.filter(id__gt=self.id).order_by('id').first()


# 幻灯片
class Carousel(models.Model):
    number = models.IntegerField('编号', help_text='编号决定图片播放的顺序，图片不要多于5张')
    title = models.CharField('标题', max_length=20, blank=True, null=True, help_text='标题可以为空')
    content = models.CharField('描述', max_length=80)
    img_url = models.CharField('图片地址', max_length=200)
    url = models.CharField('跳转链接', max_length=200, default='#', help_text='图片跳转的超链接，默认#表示不跳转')

    class Meta:
        verbose_name = '图片轮播'
        verbose_name_plural = verbose_name
        # 编号越小越靠前，添加的时间约晚约靠前
        ordering = ['number', '-id']

    def __str__(self):
        return self.content[:25]

blog/views.py
import markdown
import time, datetime
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from django.conf import settings
from django.core.cache import cache
from markdown.extensions.toc import TocExtension  # 锚点的拓展
from haystack.generic_views import SearchView  # 导入搜索视图
from haystack.query import SearchQuerySet

from .models import Article, Tag, Category


class IndexView(ListView):
    """
        首页视图,继承自ListVIew，用于展示从数据库中获取的文章列表
    """
    # 获取数据库中的文章列表
    model = Article
    # template_name属性用于指定使用哪个模板进行渲染
    template_name = 'blog/index.html'
    # context_object_name属性用于给上下文变量取名（在模板中使用该名字）
    context_object_name = 'article_list'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', None)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 0)

    def get_ordering(self):
        ordering = super().get_ordering()
        sort = self.kwargs.get('sort')
        if sort == 'v':
            return ('-views', '-update_date', '-id')
        return ordering


class ArchiveView(ListView):
    model = Article
    template_name = 'blog/archive.html'
    context_object_name = 'article_list'
    paginate_by = 200
    paginate_orphans = 50


class CategoryView(ListView):
    model = Article
    template_name = 'blog/category.html'
    context_object_name = 'article_list'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', None)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 0)

    def get_ordering(self):
        ordering = super().get_ordering()
        sort = self.kwargs.get('sort')
        if sort == 'v':
            return ('-views', '-update_date', '-id')
        return ordering

    # 重写通用视图的get_queryset方法，获取定制数据
    # 该方法默认获取指定模型的全部列表数据
    def get_queryset(self):
        queryset = super().get_queryset()
        cate = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        return queryset.filter(category=cate)

    # 重写通用视图的get_context_data方法，获取定制模板变量字典
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cate = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        context['search_tag'] = '文章分类'
        context['search_instance'] = cate
        return context


class TagView(ListView):
    model = Article
    template_name = 'blog/tag.html'
    context_object_name = 'article_list'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', None)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 0)

    def get_ordering(self):
        ordering = super().get_ordering()
        sort = self.kwargs.get('sort')
        if sort == 'v':
            return ('-views', '-update_date', '-id')
        return ordering

    def get_queryset(self):
        queryset = super().get_queryset()
        tag = get_object_or_404(Tag, slug=self.kwargs.get('slug'))
        return queryset.filter(tags=tag)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = get_object_or_404(Tag, slug=self.kwargs.get('slug'))
        context['search_tag'] = '文章标签'
        context['search_instance'] = tag
        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/detail.html'
    context_object_name = 'article'

    def get_object(self):
        obj = super().get_object()
        # 设置浏览量增加时间判断,同一篇文章两次浏览超过五分钟才重新统计阅览量
        u = self.request.user
        ses = self.request.session
        the_key = 'is_read_{}'.format(obj.id)
        is_read_time = ses.get(the_key)
        if not is_read_time:
            obj.update_views()
            ses[the_key] = time.time()
        else:
            now_time = time.time()
            t = now_time - is_read_time
            if t > 60 * 5:
                obj.update_views()
                ses[the_key] = time.time()
        
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])
        obj.body = md.convert(obj.body)
        obj.toc = md.toc
        return obj


def AboutView(request):
    site_date = datetime.datetime.strptime('2020-05-30','%Y-%m-%d')
    return render(request, 'blog/about.html',context={'site_date':site_date})


# 重写搜索视图，可以增加一些额外的参数，且可以重新定义名称
class MySearchView(SearchView):
    context_object_name = 'search_list'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', None)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 0)
    queryset = SearchQuerySet().order_by('-views')

blog/templates/blog/tags/article_list.html
{% load blog_tags oauth_tags comment_tags %}

<div class="summary-list">
    {% for article in article_list %}
    <div class="media mb-1 mb-sm-2 p-2 p-lg-3">
        <div class="align-self-center mr-2 mr-lg-3 w-25 modal-open">
            <a href="{{ article.get_absolute_url }}">
                <img class="w-100 article-img" src="{{ article.img_link }}" alt="{{ article.title }}">
            </a>
        </div>
        <div class="media-body">
            <div class="text-muted mb-2 f-12">
                {% get_user_avatar_tag article.author %}
                <span>{{ article.author }}</span>
                <span><i class="fa fa-calendar-times-o ml-2 mr-1"></i>{{ article.create_date }}</span>
            </div>
            <h2 class="mt-0 font-weight-bold text-info f-17">
                <a href="{{ article.get_absolute_url }}">{{ article.title}}</a>
            </h2>
            <p class="d-none d-sm-block mb-2 f-15">{{ article.summary|truncatechars:130 }}</p>
            <p class="d-block d-sm-none mb-2 f-15">{{ article.summary|truncatechars:64 }}</p>
            <div class="text-muted mb-0 f-12">
                <a class="cate" href="{{ article.category.get_absolute_url }}" title="查看当前分类下更多文章">
                    <i class="fa fa-book mr-1"></i>{{ article.category }}</a>
                <span><i class="fa fa-eye ml-2 mr-1"></i>{{ article.views }}</span>
                <a href="{{ article.get_absolute_url }}#comment-block" target="_blank" title="查看文章评论">
                    <i class="fa fa-comments ml-2 mr-1">{% get_comment_count article %}</i></a>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="p-3 mt-3 bg-white"><p>暂时没有文章!</p></div>
    {% endfor %}
</div>

blog/templates/blog/tags/base_right.html
{% load static %}
{% load blog_tags tools_tags %}

<!--个人空间-->
<div class="card border-0 rounded-0 px-3 mb-2 mb-md-3 d-none d-lg-block" id="home-card">
    <div class="card-header bg-white px-0">
        <strong><i class="fa fa-paper-plane mr-2 f-17"></i>个人空间</strong>
    </div>
    <div class="card-body px-0 pt-3 pb-1">
        <div class="row text-center">
            <div class="col">
                <a href="https://github.com/Longafter" target="_blank" title="进入博主的Github查看博客源码">
                    <img style="max-width:40px" alt="博主的github" src="{% static 'blog/img/github.png' %}">
                    <p class="mt-2">Github</p>
                </a>
            </div>
            <div class="col">
                <a href="{% url 'tools:timeline'%}" title="查看网站建站历程">
                    <img style="max-width:40px" alt="网站的建站历程" src="{% static 'blog/img/blog.png' %}">
                    <p class="mt-2">Timeline</p>
                </a>
            </div>
            <div class="col">
                <a href="" target="_blank" title="订阅博客">
                    <img style="max-width:40px" alt="订阅博客RSS" src="{% static 'blog/img/rss.png' %}">
                    <p class="mt-2">RSS订阅</p>
                </a>
            </div>
        </div>
    </div>
</div>
<!--文章分类-->
<div class="card border-0 rounded-0 px-3 mb-2 mb-md-3" id="category-card">
    <div class="card-header bg-white px-0">
        <strong><i class="fa fa-book mr-2 f-17"></i>文章分类</strong>
    </div>
    {% get_category_list as categories %}
    <ul class="list-group list-group-flush f-16">
        {% for each in categories %}
        <li class="list-group-item d-flex justify-content-between align-items-center pr-2 py-2">
            <a class="category-item" href="{{ each.get_absolute_url }}"
               title="查看【{{ each.name }}】分类下所有文章">{{ each.name }}</a>
            <span class="badge text-center" title="当前分类下有{{ each.total_num }}篇文章">{{ each.total_num }}</span>
        </li>
        {% endfor %}
    </ul>
</div>
<!--标签云-->
<div class="card border-0 rounded-0 px-3 mb-2 mb-md-3" id="tag-card">
    <div class="card-header bg-white px-0">
        <strong><i class="fa fa-tags mr-2 f-17"></i>标&nbsp;签&nbsp;云</strong>
    </div>
    <div class="card-body px-0 py-3">
        <div class="tag-cloud">
            {% get_tag_list as tag_list %}
            {% for tag in tag_list %}
            <a href="{{ tag.get_absolute_url }}" class="tags f-16" id="tag-{{ forloop.counter }}"
               title="【{{ tag.name }}】标签下有{{ tag.total_num }}篇文章">{{ tag.name }}</a>
            {% endfor %}
        </div>
    </div>
</div>
<!--友链-->
<div class="d-none d-lg-block">
    <div class="card border-0 rounded-0 px-3 mb-2 mb-md-3" id="friends-card">
        <div class="card-header bg-white px-0">
            <strong><i class="fa fa-link mr-2 f-17"></i>友情链接</strong>
        </div>
        <div class="card-body px-0 py-3">
            <div class="tool-list">
                {% get_friends as friends %}
                {% for friend in friends %}
                <div class="w-50 float-left text-center mb-2">
                    <div class="mx-2">
                        <a href="{{ friend.link }}" title="{{ friend.description }}" target="_blank">
                            {{ friend.name }}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

blog/templates/blog/tags/carousel.html
{% load static %}
{% load blog_tags %}

{% get_carousel_list as carousels %}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        {% for each in carousels %}
        {% if forloop.counter0 == 0 %}
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        {% else %}
        <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}"></li>
        {% endif %}
        {% endfor %}
    </ol>
    <div class="carousel-inner">
        {% for each in carousels %}
            {% if forloop.counter0 == 0 %}
            <div class="carousel-item active">
            {% else %}
            <div class="carousel-item">
            {% endif %}
                <a href="{{ each.url }}">
                    <img class="w-100" src="{{ each.img_url }}" alt="{{ each.content }}">
                </a>
            </div>
        {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

blog/templates/blog/tags/navbar.html
{% load static %}
{% load oauth_tags comment_tags %}

<nav class="navbar navbar-expand-md bg-white fixed-top blog-navbar py-md-0">
    <a class="navbar-brand d-md-none d-lg-block" id="site-logo-name" href="/">
        <strong class="px-2">左撇子招牌字</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-2">
                {% url 'blog:index' as index_url %}
                <a class="nav-link py-md-3 {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}"><i class="fa fa-home mr-1"></i>首页<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item mr-2">
                {% url 'blog:archive' as archive_url %}
                <a class="nav-link py-md-3 {% if request.path == archive_url %}active{% endif %}" href="{{ archive_url }}"><i class="fa fa-sitemap mr-1"></i>归档</a>
            </li>
            <li class="nav-item mr-2 ">
                {% url 'blog:about' as about_url %}
                <a class="nav-link py-md-3 {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}"><i class="fa fa-anchor mr-1"></i>关于</a>
            </li>
            <form class="nav-item navbar-form mr-2 py-md-2" role="search" method="get" id="searchform" action="{% url 'blog:search_view'%}">
                <div class="input-group">
                    <input type="search" name="q" class="form-control rounded-0 f-15" placeholder="搜索" required=True>
                    <div class="input-group-btn">
                        <button class="btn btn-info rounded-0" type="submit"><i class="fa fa-search"></i></button>
                    </div>
                </div><!-- /input-group -->
            </form>
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            {% get_notifications_count user 'false' as msgnum %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false" title="{{ user.username }}，欢迎回来！">
                    {% if msgnum > 0%}
                    <span class="get-msg text-center">{{ msgnum }}</span>
                    {% endif %}
                    {% get_user_avatar_tag user %}
                </a>
                <div class="dropdown-menu dropdown-menu-right mt-0 rounded-0 border-0" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item pl-3" href="{% url 'oauth:profile' %}"><i class="fa fa-fw fa-user text-info mr-2"></i>个人资料</a>
                    {% if user.is_staff %}
                    <a class="dropdown-item pl-3" target="_blank" href="{% url 'xadmin:index' %}"><i
                            class="fa fa-fw fa-key text-info mr-2"></i>后台管理</a>
                    {% endif %}
                    <a class="dropdown-item pl-3" href="{% url 'comment:notification' %}"><i class="fa fa-fw fa-bell text-info mr-2"></i>消息
                        {% if msgnum > 0%}
                        <span class="badge badge-warning ml-3 text-center">{{ msgnum }}</span>
                        {% endif %}
                    </a>
                    <a class="dropdown-item pl-3" href="{% url 'account_logout' %}"><i
                            class="fa fa-fw fa-sign-out text-info mr-2"></i>注销</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item mr-2">
                <a class="nav-link py-md-3" href="{% url 'account_login' %}?next={{ request.path }}">登录</a>
            </li>
            <li class="nav-item">
                <a class="nav-link py-md-3" href="{% url 'account_signup' %}?next={{ request.path }}">注册</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

blog/templates/blog/tags/pagecut.html
<div class="text-center mt-2 mt-sm-1 mt-md-0 mb-3 f-16">
    {% if page_obj.has_previous %}
    <a class="text-success" href="?page={{ page_obj.previous_page_number }}">上一页</a>
    {% else %}
    <span class="text-secondary" title="当前页已经是首页">上一页</span>
    {% endif %}
    <span class="mx-2">第&nbsp;{{ page_obj.number }}&nbsp;/&nbsp;{{ paginator.num_pages }}&nbsp;页</span>
    {% if page_obj.has_next %}
    <a class="text-success" href="?page={{ page_obj.next_page_number }}">下一页</a>
    {% else %}
    <span class="text-secondary" title="当前页已经是末页">下一页</span>
    {% endif %}
</div>